### ISSUE TITLE
Can we move this to collaborate with the CommunityRepairCafe?

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/Multi-inovative-repair-cafe#1]
Hi @mawarose 

Do you think we can move this project input over to https://github.com/ASKnet-Open-Training/CommunityRepairCafe ?

→ I think I accentually forked this twice due to the license issue first from you to me to here.
Now it is a bit confusing and holds lots of duplicated Ideas  with the CommunityRepairCafe → though I like the Idea of having a multipurpose action very much, maybe we can include this?

Especially if it comes to locally available materials is a good thought as you started to describe here
https://github.com/mawarose/Multi-inovative-repair-cafe

**Comment by mawarose** [comment]
Yah perfect 💓

**Comment by mawarose** [comment]
Yah
